#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("iCoffe.Droid.Resource", IsApplication=true)]

namespace iCoffe.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int rotate_from_down_to_up = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int rotate_from_up_to_down = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int scale_down = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int scale_up = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070011
			public const int Grey_300 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int Grey_500 = 2131165202;
			
			// aapt resource value: 0x7f07001b
			public const int button = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int button_pressed = 2131165212;
			
			// aapt resource value: 0x7f070008
			public const int common_action_bar_splitter = 2131165192;
			
			// aapt resource value: 0x7f07001f
			public const int common_google_signin_btn_text_dark = 2131165215;
			
			// aapt resource value: 0x7f070009
			public const int common_google_signin_btn_text_dark_default = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_signin_btn_text_dark_disabled = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_signin_btn_text_dark_focused = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_signin_btn_text_dark_pressed = 2131165194;
			
			// aapt resource value: 0x7f070020
			public const int common_google_signin_btn_text_light = 2131165216;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_signin_btn_text_light_default = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int common_google_signin_btn_text_light_disabled = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int common_google_signin_btn_text_light_focused = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_signin_btn_text_light_pressed = 2131165198;
			
			// aapt resource value: 0x7f070021
			public const int common_plus_signin_btn_text_dark = 2131165217;
			
			// aapt resource value: 0x7f070000
			public const int common_plus_signin_btn_text_dark_default = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int common_plus_signin_btn_text_dark_disabled = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_plus_signin_btn_text_dark_focused = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_plus_signin_btn_text_dark_pressed = 2131165185;
			
			// aapt resource value: 0x7f070022
			public const int common_plus_signin_btn_text_light = 2131165218;
			
			// aapt resource value: 0x7f070004
			public const int common_plus_signin_btn_text_light_default = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int common_plus_signin_btn_text_light_disabled = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_plus_signin_btn_text_light_focused = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int common_plus_signin_btn_text_light_pressed = 2131165189;
			
			// aapt resource value: 0x7f070015
			public const int default_color = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int focused_color = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int pressed_color = 2131165203;
			
			// aapt resource value: 0x7f07001d
			public const int red_main = 2131165213;
			
			// aapt resource value: 0x7f070019
			public const int sign_in_sign_button = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int sign_in_skip_button = 2131165210;
			
			// aapt resource value: 0x7f070023
			public const int text_tab = 2131165219;
			
			// aapt resource value: 0x7f07001e
			public const int translucent_black = 2131165214;
			
			// aapt resource value: 0x7f070016
			public const int white_bg = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int white_bg_50 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int white_bg_70 = 2131165208;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080002
			public const int ball_radius = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int font_size = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int sign_in_button_margin = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int sign_in_edit_height = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int sign_in_edit_margin = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int textview_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int textview_width = 2131230721;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_transparent_corned = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_white_50_corned = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_white_70_corned = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg_white_corned = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bonus_tab = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_test_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_full_open_on_phone = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_dark_disabled = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_dark_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_light_disabled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_icon_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_icon_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_icon_light_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_dark_disabled = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_dark_focused = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_dark_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_dark_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_text_light_disabled = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_text_light_focused = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_text_light_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_text_light_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_ic_googleplayservices = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_dark_focused = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_dark_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_icon_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_icon_light_disabled = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_icon_light_focused = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_icon_light_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_icon_light_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_dark_disabled = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_dark_focused = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_dark_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_text_dark_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_plus_signin_btn_text_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_plus_signin_btn_text_light_disabled = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_plus_signin_btn_text_light_focused = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_plus_signin_btn_text_light_normal = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_plus_signin_btn_text_light_pressed = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int event_desc_gift_button = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_account_box_white_24dp = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_bonus_logo_demo_120dp = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_bonus_logo_demo_96dp = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_bonus_red_48dp = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_bonus_red_60dp = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_bonus_white_48dp = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_cake_white_24dp = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_cake_white_36dp = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_cake_white_48dp = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_free_breakfast_white_24dp = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_free_breakfast_white_48dp = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_grade_black_24dp = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_lock_outline_white_24dp = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_map_red_48dp = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_map_white_48dp = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_place_white_18dp = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_place_white_24dp = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_place_white_48dp = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_scroll_markers_1_from_2_24dp = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_scroll_markers_1_from_2_36dp = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic_scroll_markers_2_from_2_24dp = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ic_scroll_markers_2_from_2_36dp = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ic_star_red_24dp = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ic_user_red_48dp = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ic_user_white_48dp = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int Icon = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int map_tab = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int new_splash_screen = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int NewIcon = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int redhat = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int round_red = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int Splash = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int Splash2 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int splash_screen = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int Splinter_Cell = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int Splinter_Cell_2 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int top_nav_states = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int tutorial_1 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int tutorial_2 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int user_tab = 2130837594;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a0014
			public const int afExitB = 2131361812;
			
			// aapt resource value: 0x7f0a0016
			public const int afListView = 2131361814;
			
			// aapt resource value: 0x7f0a000d
			public const int afMainLL = 2131361805;
			
			// aapt resource value: 0x7f0a0015
			public const int afShowAndHideMapB = 2131361813;
			
			// aapt resource value: 0x7f0a000e
			public const int afUserInfoLL = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int afUserLoginTV = 2131361807;
			
			// aapt resource value: 0x7f0a0013
			public const int afUserMap = 2131361811;
			
			// aapt resource value: 0x7f0a0012
			public const int afUserMapFL = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int afUserNameTV = 2131361809;
			
			// aapt resource value: 0x7f0a0010
			public const int afUserPointsAmountTV = 2131361808;
			
			// aapt resource value: 0x7f0a000a
			public const int auto = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int dark = 2131361803;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int icon_only = 2131361799;
			
			// aapt resource value: 0x7f0a004b
			public const int imageView1 = 2131361867;
			
			// aapt resource value: 0x7f0a000c
			public const int light = 2131361804;
			
			// aapt resource value: 0x7f0a004c
			public const int linearLayout1 = 2131361868;
			
			// aapt resource value: 0x7f0a002e
			public const int lock_message = 2131361838;
			
			// aapt resource value: 0x7f0a002d
			public const int locker = 2131361837;
			
			// aapt resource value: 0x7f0a001a
			public const int mContentFL = 2131361818;
			
			// aapt resource value: 0x7f0a0017
			public const int maBonusTabLL = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int maMapTabLL = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int maUserTabLL = 2131361817;
			
			// aapt resource value: 0x7f0a001b
			public const int mfContentFL = 2131361819;
			
			// aapt resource value: 0x7f0a001d
			public const int mfFadeV = 2131361821;
			
			// aapt resource value: 0x7f0a001c
			public const int mfMap = 2131361820;
			
			// aapt resource value: 0x7f0a001e
			public const int mfOffersLV = 2131361822;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a002a
			public const int oaAddressTV = 2131361834;
			
			// aapt resource value: 0x7f0a0028
			public const int oaBonusDescrTV = 2131361832;
			
			// aapt resource value: 0x7f0a002b
			public const int oaBottomLL = 2131361835;
			
			// aapt resource value: 0x7f0a0024
			public const int oaCafeImageIV = 2131361828;
			
			// aapt resource value: 0x7f0a0022
			public const int oaCafeNameIV = 2131361826;
			
			// aapt resource value: 0x7f0a0021
			public const int oaCafeNameRL = 2131361825;
			
			// aapt resource value: 0x7f0a0023
			public const int oaCafeNameTV = 2131361827;
			
			// aapt resource value: 0x7f0a001f
			public const int oaMainLL = 2131361823;
			
			// aapt resource value: 0x7f0a0026
			public const int oaMiddleLL = 2131361830;
			
			// aapt resource value: 0x7f0a0027
			public const int oaMiddleLeftLL = 2131361831;
			
			// aapt resource value: 0x7f0a0029
			public const int oaMiddleRightLL = 2131361833;
			
			// aapt resource value: 0x7f0a0025
			public const int oaPriceTV = 2131361829;
			
			// aapt resource value: 0x7f0a0020
			public const int oaTopLL = 2131361824;
			
			// aapt resource value: 0x7f0a002c
			public const int oaWantB = 2131361836;
			
			// aapt resource value: 0x7f0a0033
			public const int ofListView = 2131361843;
			
			// aapt resource value: 0x7f0a0032
			public const int ofMainLL = 2131361842;
			
			// aapt resource value: 0x7f0a0030
			public const int oiGiftIV = 2131361840;
			
			// aapt resource value: 0x7f0a002f
			public const int oiOfferLogoIV = 2131361839;
			
			// aapt resource value: 0x7f0a0031
			public const int oiOfferTitleTV = 2131361841;
			
			// aapt resource value: 0x7f0a0035
			public const int poiGiftIV = 2131361845;
			
			// aapt resource value: 0x7f0a0034
			public const int poiOfferLogoIV = 2131361844;
			
			// aapt resource value: 0x7f0a0036
			public const int poiOfferTitleTV = 2131361846;
			
			// aapt resource value: 0x7f0a004f
			public const int relativeLayout1 = 2131361871;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a003b
			public const int siEmailET = 2131361851;
			
			// aapt resource value: 0x7f0a003a
			public const int siEmailIV = 2131361850;
			
			// aapt resource value: 0x7f0a0038
			public const int siEmailLL = 2131361848;
			
			// aapt resource value: 0x7f0a0037
			public const int siMainRL = 2131361847;
			
			// aapt resource value: 0x7f0a003e
			public const int siPasswordET = 2131361854;
			
			// aapt resource value: 0x7f0a003d
			public const int siPasswordIV = 2131361853;
			
			// aapt resource value: 0x7f0a0039
			public const int siPasswordLL = 2131361849;
			
			// aapt resource value: 0x7f0a003c
			public const int siSigninB = 2131361852;
			
			// aapt resource value: 0x7f0a003f
			public const int siSignupB = 2131361855;
			
			// aapt resource value: 0x7f0a0008
			public const int standard = 2131361800;
			
			// aapt resource value: 0x7f0a0049
			public const int suConfirmET = 2131361865;
			
			// aapt resource value: 0x7f0a0048
			public const int suConfirmIV = 2131361864;
			
			// aapt resource value: 0x7f0a0045
			public const int suConfirmLL = 2131361861;
			
			// aapt resource value: 0x7f0a0044
			public const int suEmailET = 2131361860;
			
			// aapt resource value: 0x7f0a0043
			public const int suEmailIV = 2131361859;
			
			// aapt resource value: 0x7f0a0041
			public const int suEmailLL = 2131361857;
			
			// aapt resource value: 0x7f0a0040
			public const int suMainRL = 2131361856;
			
			// aapt resource value: 0x7f0a0047
			public const int suPasswordET = 2131361863;
			
			// aapt resource value: 0x7f0a0046
			public const int suPasswordIV = 2131361862;
			
			// aapt resource value: 0x7f0a0042
			public const int suPasswordLL = 2131361858;
			
			// aapt resource value: 0x7f0a004a
			public const int suSignupB = 2131361866;
			
			// aapt resource value: 0x7f0a004e
			public const int t2fAllclearB = 2131361870;
			
			// aapt resource value: 0x7f0a004d
			public const int t2fRules = 2131361869;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a0009
			public const int wide = 2131361801;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccountFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MapFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Offer = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int OfferItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int OffersFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PurchasedOfferItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SignIn = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SignUp = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Tutorial_1_Fragment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Tutorial_2_Fragment = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050020
			public const int app_name = 2131034144;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f050023
			public const int cancel_button = 2131034147;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_api_unavailable_text = 2131034136;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_enable_button = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_enable_text = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_enable_title = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_install_button = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_text_phone = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_install_text_tablet = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_title = 2131034116;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_invalid_account_text = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_invalid_account_title = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int common_google_play_services_network_error_text = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_network_error_title = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_notification_ticker = 2131034115;
			
			// aapt resource value: 0x7f05001c
			public const int common_google_play_services_restricted_profile_text = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_restricted_profile_title = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_sign_in_failed_text = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_sign_in_failed_title = 2131034137;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_unknown_issue = 2131034114;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_unsupported_text = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int common_google_play_services_unsupported_title = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_update_button = 2131034134;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_update_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_update_title = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_updating_text = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_updating_title = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_wear_update_text = 2131034125;
			
			// aapt resource value: 0x7f050017
			public const int common_open_on_phone = 2131034135;
			
			// aapt resource value: 0x7f05001d
			public const int common_signin_button_text = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int common_signin_button_text_long = 2131034142;
			
			// aapt resource value: 0x7f050021
			public const int error_caption = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int hello = 2131034143;
			
			// aapt resource value: 0x7f050029
			public const int lorem_ipsum_long = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int lorem_ipsum_short = 2131034152;
			
			// aapt resource value: 0x7f050024
			public const int no_internet_connection = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int no_internet_provider = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int no_location_provider = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int on_button = 2131034151;
			
			// aapt resource value: 0x7f05002b
			public const int repush_for_exit = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int tutorial_rules = 2131034154;
			
			// aapt resource value: 0x7f050022
			public const int warning_caption = 2131034146;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int MyTheme_Splash = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
