#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("iCoffe.Droid.Resource", IsApplication=true)]

namespace iCoffe.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int Grey_300 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Grey_500 = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int default_color = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int focused_color = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int pressed_color = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int sign_in_sign_button = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int sign_in_skip_button = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int white_bg = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050002
			public const int ball_radius = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int font_size = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int sign_in_button_margin = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int sign_in_edit_height = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int sign_in_edit_margin = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int textview_height = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textview_width = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_white_corned = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_test_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int event_desc_gift_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_account_box_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_cake_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_cake_white_36dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_cake_white_48dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_free_breakfast_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_free_breakfast_white_48dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_lock_outline_white_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_place_white_18dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_place_white_24dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_place_white_48dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int redhat = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int sign_in_reg_button = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int sign_in_sign_button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sign_in_skip_button = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int splash_screen = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Splinter_Cell = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Splinter_Cell_2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int top_nav_states = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int edAddressesTV = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int edBottomLL = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int edContactsRL = 2131230733;
			
			// aapt resource value: 0x7f080005
			public const int edEventImageIV = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int edEventNameIV = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int edEventNameRL = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int edEventNameTV = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int edGiftBtn = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int edMainLL = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int edMiddleLL = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int edMiddleLeftLL = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int edMiddleRightLL = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int edOperTimesTV = 2131230731;
			
			// aapt resource value: 0x7f08000f
			public const int edPhoneTV = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int edSiteTV = 2131230734;
			
			// aapt resource value: 0x7f080001
			public const int edTopLL = 2131230721;
			
			// aapt resource value: 0x7f080012
			public const int frListView = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int frMainLL = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int frTextView = 2131230737;
			
			// aapt resource value: 0x7f08001d
			public const int ivMap = 2131230749;
			
			// aapt resource value: 0x7f08001b
			public const int ivNets = 2131230747;
			
			// aapt resource value: 0x7f08001f
			public const int ivUser = 2131230751;
			
			// aapt resource value: 0x7f080019
			public const int linearLayout1 = 2131230745;
			
			// aapt resource value: 0x7f080020
			public const int mContentFL = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int mvMap = 2131230753;
			
			// aapt resource value: 0x7f080018
			public const int niImageHasGifts = 2131230744;
			
			// aapt resource value: 0x7f080017
			public const int niImageHasGiftsRL = 2131230743;
			
			// aapt resource value: 0x7f080014
			public const int niImageLogo = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int niImageLogoRL = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int niText = 2131230742;
			
			// aapt resource value: 0x7f080015
			public const int niTextRL = 2131230741;
			
			// aapt resource value: 0x7f08002b
			public const int rCityET = 2131230763;
			
			// aapt resource value: 0x7f08002a
			public const int rCityIV = 2131230762;
			
			// aapt resource value: 0x7f080029
			public const int rCityLL = 2131230761;
			
			// aapt resource value: 0x7f080034
			public const int rConfirmET = 2131230772;
			
			// aapt resource value: 0x7f080033
			public const int rConfirmIV = 2131230771;
			
			// aapt resource value: 0x7f080032
			public const int rConfirmLL = 2131230770;
			
			// aapt resource value: 0x7f08002e
			public const int rEmailET = 2131230766;
			
			// aapt resource value: 0x7f08002d
			public const int rEmailIV = 2131230765;
			
			// aapt resource value: 0x7f08002c
			public const int rEmailLL = 2131230764;
			
			// aapt resource value: 0x7f080036
			public const int rExitBtn = 2131230774;
			
			// aapt resource value: 0x7f080028
			public const int rFirstNameET = 2131230760;
			
			// aapt resource value: 0x7f080027
			public const int rFirstNameIV = 2131230759;
			
			// aapt resource value: 0x7f080026
			public const int rFirstNameLL = 2131230758;
			
			// aapt resource value: 0x7f080025
			public const int rLastNameET = 2131230757;
			
			// aapt resource value: 0x7f080024
			public const int rLastNameIV = 2131230756;
			
			// aapt resource value: 0x7f080023
			public const int rLastNameLL = 2131230755;
			
			// aapt resource value: 0x7f080022
			public const int rMainRL = 2131230754;
			
			// aapt resource value: 0x7f080031
			public const int rPasswordET = 2131230769;
			
			// aapt resource value: 0x7f080030
			public const int rPasswordIV = 2131230768;
			
			// aapt resource value: 0x7f08002f
			public const int rPasswordLL = 2131230767;
			
			// aapt resource value: 0x7f080035
			public const int rRegisterBtn = 2131230773;
			
			// aapt resource value: 0x7f080037
			public const int relativeLayout1 = 2131230775;
			
			// aapt resource value: 0x7f08003a
			public const int rlIcon1 = 2131230778;
			
			// aapt resource value: 0x7f08003e
			public const int rlIcon2 = 2131230782;
			
			// aapt resource value: 0x7f08001c
			public const int rlMap = 2131230748;
			
			// aapt resource value: 0x7f08001a
			public const int rlNets = 2131230746;
			
			// aapt resource value: 0x7f08001e
			public const int rlUser = 2131230750;
			
			// aapt resource value: 0x7f080038
			public const int siEdit1 = 2131230776;
			
			// aapt resource value: 0x7f080039
			public const int siEdit2 = 2131230777;
			
			// aapt resource value: 0x7f08003c
			public const int siEmailET = 2131230780;
			
			// aapt resource value: 0x7f08003b
			public const int siEmailIV = 2131230779;
			
			// aapt resource value: 0x7f080040
			public const int siPasswordET = 2131230784;
			
			// aapt resource value: 0x7f08003f
			public const int siPasswordIV = 2131230783;
			
			// aapt resource value: 0x7f080042
			public const int siRegBtn = 2131230786;
			
			// aapt resource value: 0x7f08003d
			public const int siSignBtn = 2131230781;
			
			// aapt resource value: 0x7f080041
			public const int siSkipBtn = 2131230785;
			
			// aapt resource value: 0x7f080048
			public const int ufCityIV = 2131230792;
			
			// aapt resource value: 0x7f080047
			public const int ufCityLL = 2131230791;
			
			// aapt resource value: 0x7f080049
			public const int ufCityTV = 2131230793;
			
			// aapt resource value: 0x7f08004b
			public const int ufListView = 2131230795;
			
			// aapt resource value: 0x7f080043
			public const int ufMainLL = 2131230787;
			
			// aapt resource value: 0x7f08004a
			public const int ufTextView = 2131230794;
			
			// aapt resource value: 0x7f080045
			public const int ufUserAvatarIV = 2131230789;
			
			// aapt resource value: 0x7f080044
			public const int ufUserInfoRL = 2131230788;
			
			// aapt resource value: 0x7f080046
			public const int ufUserNameTV = 2131230790;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EventDesc = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GiftItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MapFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NetItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Reg = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SignIn = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int UserFragment = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int cancel_button = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int error_caption = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int no_internet_connection = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int no_internet_provider = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int no_location_provider = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int on_button = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int warning_caption = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
