#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("iCoffe.Droid.Resource", IsApplication=true)]

namespace iCoffe.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060011
			public const int Grey_300 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int Grey_500 = 2131099666;
			
			// aapt resource value: 0x7f060008
			public const int common_action_bar_splitter = 2131099656;
			
			// aapt resource value: 0x7f060019
			public const int common_google_signin_btn_text_dark = 2131099673;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_dark_default = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_dark_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_signin_btn_text_dark_focused = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark_pressed = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int common_google_signin_btn_text_light = 2131099674;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_signin_btn_text_light_default = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_light_disabled = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light_focused = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_signin_btn_text_light_pressed = 2131099662;
			
			// aapt resource value: 0x7f06001b
			public const int common_plus_signin_btn_text_dark = 2131099675;
			
			// aapt resource value: 0x7f060000
			public const int common_plus_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_plus_signin_btn_text_dark_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_plus_signin_btn_text_dark_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_plus_signin_btn_text_dark_pressed = 2131099649;
			
			// aapt resource value: 0x7f06001c
			public const int common_plus_signin_btn_text_light = 2131099676;
			
			// aapt resource value: 0x7f060004
			public const int common_plus_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_plus_signin_btn_text_light_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_plus_signin_btn_text_light_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_plus_signin_btn_text_light_pressed = 2131099653;
			
			// aapt resource value: 0x7f060015
			public const int default_color = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int focused_color = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int pressed_color = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int sign_in_sign_button = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int sign_in_skip_button = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int white_bg = 2131099670;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070002
			public const int ball_radius = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int font_size = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int sign_in_button_margin = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int sign_in_edit_height = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int sign_in_edit_margin = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int textview_height = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int textview_width = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_white_corned = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_test_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_full_open_on_phone = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_disabled = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_disabled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_disabled = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_focused = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_ic_googleplayservices = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_dark_focused = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_dark_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_disabled = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_light_focused = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_light_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_icon_light_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_disabled = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_dark_focused = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_dark_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_dark_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_disabled = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_light_focused = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_light_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_text_light_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int event_desc_gift_button = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_account_box_white_24dp = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_cake_white_24dp = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_cake_white_36dp = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_cake_white_48dp = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_free_breakfast_white_24dp = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_free_breakfast_white_48dp = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_lock_outline_white_24dp = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_place_white_18dp = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_place_white_24dp = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_place_white_48dp = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Icon = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int redhat = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int sign_in_reg_button = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int sign_in_sign_button = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int sign_in_skip_button = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int splash_screen = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int Splinter_Cell = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Splinter_Cell_2 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int top_nav_states = 2130837568;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090005
			public const int adjust_height = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int adjust_width = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int auto = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int dark = 2131296267;
			
			// aapt resource value: 0x7f090016
			public const int edAddressesTV = 2131296278;
			
			// aapt resource value: 0x7f090019
			public const int edBottomLL = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int edContactsRL = 2131296282;
			
			// aapt resource value: 0x7f090012
			public const int edEventImageIV = 2131296274;
			
			// aapt resource value: 0x7f090010
			public const int edEventNameIV = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int edEventNameRL = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int edEventNameTV = 2131296273;
			
			// aapt resource value: 0x7f090013
			public const int edGiftBtn = 2131296275;
			
			// aapt resource value: 0x7f09000d
			public const int edMainLL = 2131296269;
			
			// aapt resource value: 0x7f090014
			public const int edMiddleLL = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int edMiddleLeftLL = 2131296277;
			
			// aapt resource value: 0x7f090017
			public const int edMiddleRightLL = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int edOperTimesTV = 2131296280;
			
			// aapt resource value: 0x7f09001c
			public const int edPhoneTV = 2131296284;
			
			// aapt resource value: 0x7f09001b
			public const int edSiteTV = 2131296283;
			
			// aapt resource value: 0x7f09000e
			public const int edTopLL = 2131296270;
			
			// aapt resource value: 0x7f09001f
			public const int frListView = 2131296287;
			
			// aapt resource value: 0x7f09001d
			public const int frMainLL = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int frTextView = 2131296286;
			
			// aapt resource value: 0x7f090000
			public const int hybrid = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int icon_only = 2131296263;
			
			// aapt resource value: 0x7f09002a
			public const int ivMap = 2131296298;
			
			// aapt resource value: 0x7f090028
			public const int ivNets = 2131296296;
			
			// aapt resource value: 0x7f09002c
			public const int ivUser = 2131296300;
			
			// aapt resource value: 0x7f09000c
			public const int light = 2131296268;
			
			// aapt resource value: 0x7f090026
			public const int linearLayout1 = 2131296294;
			
			// aapt resource value: 0x7f09002d
			public const int mContentFL = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int mvMap = 2131296302;
			
			// aapt resource value: 0x7f090025
			public const int niImageHasGifts = 2131296293;
			
			// aapt resource value: 0x7f090024
			public const int niImageHasGiftsRL = 2131296292;
			
			// aapt resource value: 0x7f090021
			public const int niImageLogo = 2131296289;
			
			// aapt resource value: 0x7f090020
			public const int niImageLogoRL = 2131296288;
			
			// aapt resource value: 0x7f090023
			public const int niText = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int niTextRL = 2131296290;
			
			// aapt resource value: 0x7f090001
			public const int none = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int normal = 2131296258;
			
			// aapt resource value: 0x7f090038
			public const int rCityET = 2131296312;
			
			// aapt resource value: 0x7f090037
			public const int rCityIV = 2131296311;
			
			// aapt resource value: 0x7f090036
			public const int rCityLL = 2131296310;
			
			// aapt resource value: 0x7f090041
			public const int rConfirmET = 2131296321;
			
			// aapt resource value: 0x7f090040
			public const int rConfirmIV = 2131296320;
			
			// aapt resource value: 0x7f09003f
			public const int rConfirmLL = 2131296319;
			
			// aapt resource value: 0x7f09003b
			public const int rEmailET = 2131296315;
			
			// aapt resource value: 0x7f09003a
			public const int rEmailIV = 2131296314;
			
			// aapt resource value: 0x7f090039
			public const int rEmailLL = 2131296313;
			
			// aapt resource value: 0x7f090043
			public const int rExitBtn = 2131296323;
			
			// aapt resource value: 0x7f090035
			public const int rFirstNameET = 2131296309;
			
			// aapt resource value: 0x7f090034
			public const int rFirstNameIV = 2131296308;
			
			// aapt resource value: 0x7f090033
			public const int rFirstNameLL = 2131296307;
			
			// aapt resource value: 0x7f090032
			public const int rLastNameET = 2131296306;
			
			// aapt resource value: 0x7f090031
			public const int rLastNameIV = 2131296305;
			
			// aapt resource value: 0x7f090030
			public const int rLastNameLL = 2131296304;
			
			// aapt resource value: 0x7f09002f
			public const int rMainRL = 2131296303;
			
			// aapt resource value: 0x7f09003e
			public const int rPasswordET = 2131296318;
			
			// aapt resource value: 0x7f09003d
			public const int rPasswordIV = 2131296317;
			
			// aapt resource value: 0x7f09003c
			public const int rPasswordLL = 2131296316;
			
			// aapt resource value: 0x7f090042
			public const int rRegisterBtn = 2131296322;
			
			// aapt resource value: 0x7f090044
			public const int relativeLayout1 = 2131296324;
			
			// aapt resource value: 0x7f090047
			public const int rlIcon1 = 2131296327;
			
			// aapt resource value: 0x7f09004b
			public const int rlIcon2 = 2131296331;
			
			// aapt resource value: 0x7f090029
			public const int rlMap = 2131296297;
			
			// aapt resource value: 0x7f090027
			public const int rlNets = 2131296295;
			
			// aapt resource value: 0x7f09002b
			public const int rlUser = 2131296299;
			
			// aapt resource value: 0x7f090003
			public const int satellite = 2131296259;
			
			// aapt resource value: 0x7f090045
			public const int siEdit1 = 2131296325;
			
			// aapt resource value: 0x7f090046
			public const int siEdit2 = 2131296326;
			
			// aapt resource value: 0x7f090049
			public const int siEmailET = 2131296329;
			
			// aapt resource value: 0x7f090048
			public const int siEmailIV = 2131296328;
			
			// aapt resource value: 0x7f09004d
			public const int siPasswordET = 2131296333;
			
			// aapt resource value: 0x7f09004c
			public const int siPasswordIV = 2131296332;
			
			// aapt resource value: 0x7f09004f
			public const int siRegBtn = 2131296335;
			
			// aapt resource value: 0x7f09004a
			public const int siSignBtn = 2131296330;
			
			// aapt resource value: 0x7f09004e
			public const int siSkipBtn = 2131296334;
			
			// aapt resource value: 0x7f090008
			public const int standard = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int terrain = 2131296260;
			
			// aapt resource value: 0x7f090055
			public const int ufCityIV = 2131296341;
			
			// aapt resource value: 0x7f090054
			public const int ufCityLL = 2131296340;
			
			// aapt resource value: 0x7f090056
			public const int ufCityTV = 2131296342;
			
			// aapt resource value: 0x7f090058
			public const int ufListView = 2131296344;
			
			// aapt resource value: 0x7f090050
			public const int ufMainLL = 2131296336;
			
			// aapt resource value: 0x7f090057
			public const int ufTextView = 2131296343;
			
			// aapt resource value: 0x7f090052
			public const int ufUserAvatarIV = 2131296338;
			
			// aapt resource value: 0x7f090051
			public const int ufUserInfoRL = 2131296337;
			
			// aapt resource value: 0x7f090053
			public const int ufUserNameTV = 2131296339;
			
			// aapt resource value: 0x7f090009
			public const int wide = 2131296265;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EventDesc = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GiftItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MapFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NetItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Reg = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SignIn = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int UserFragment = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040020
			public const int app_name = 2130968608;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040023
			public const int cancel_button = 2130968611;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_api_unavailable_text = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_enable_text = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_enable_title = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_button = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_text_phone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_text_tablet = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_install_title = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_invalid_account_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_invalid_account_title = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_network_error_text = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_network_error_title = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_ticker = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_play_services_restricted_profile_text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_restricted_profile_title = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_sign_in_failed_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_sign_in_failed_title = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_unsupported_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_unsupported_title = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_update_button = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_title = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_updating_text = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_updating_title = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_wear_update_text = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int common_signin_button_text_long = 2130968606;
			
			// aapt resource value: 0x7f040021
			public const int error_caption = 2130968609;
			
			// aapt resource value: 0x7f04001f
			public const int hello = 2130968607;
			
			// aapt resource value: 0x7f040024
			public const int no_internet_connection = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int no_internet_provider = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int no_location_provider = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int on_button = 2130968615;
			
			// aapt resource value: 0x7f040022
			public const int warning_caption = 2130968610;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int MyTheme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
